### ISSUE TITLE
Successful submission leads to 404

### ISSUE THREAD

**Issue by ElderFuthark** [Revature-RPM/ng-ui#375]
Upon successfully submitting a project, users are greeted with a 404 error. I'm not sure if this is a bug or not. Regardless, the user should be redirected to a valid page.

![404_on_successful_submission](https://user-images.githubusercontent.com/40003119/68098485-f8863e00-fe8a-11e9-8a4a-2da8e2abfb43.jpg)

**Comment by iagosergiop93** [comment]
This error was already fixed.
